

version: "3.9"

services:
  db:
    image: postgres:15
    container_name: wellsense-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wellsense
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
   build: .
   container_name: wellsense-api
   ports:
    - "8000:8000"
   depends_on:
    - db
   environment:
    - DATABASE_URL=postgresql://postgres:postgres@db:5432/wellsense
    - SECRET_KEY=supersecretkey123
    - ALGORITHM=HS256

    
volumes:
  postgres_data: